-- migrations/001_initial_schema.sql

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  "passwordHash" TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('Leitor', 'Criador', 'Admin')),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS creators (
  id TEXT PRIMARY KEY,
  "userId" TEXT UNIQUE NOT NULL,
  "penName" TEXT NOT NULL,
  bio TEXT,
  "analyticsId" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("userId") REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS hqs (
  id TEXT PRIMARY KEY,
  "creatorId" TEXT NOT NULL,
  title TEXT NOT NULL,
  genre TEXT,
  sinopse TEXT,
  "storagePath" TEXT,
  "isPremium" BOOLEAN DEFAULT FALSE,
  "coverImage" TEXT,
  "pdfPath" TEXT,
  "pageCount" INTEGER DEFAULT 0,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("creatorId") REFERENCES creators (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "planId" TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('Active', 'Canceled')),
  "startDate" TIMESTAMP WITH TIME ZONE NOT NULL,
  "endDate" TIMESTAMP WITH TIME ZONE,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("userId") REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reading_history (
  "userId" TEXT NOT NULL,
  "hqId" TEXT NOT NULL,
  "lastPageRead" INTEGER DEFAULT 0,
  "lastReadAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("userId", "hqId"),
  FOREIGN KEY ("userId") REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY ("hqId") REFERENCES hqs (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id TEXT PRIMARY KEY,
  "adminUserId" TEXT NOT NULL,
  action TEXT NOT NULL,
  "targetType" TEXT,
  "targetId" TEXT,
  details JSONB,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("adminUserId") REFERENCES users (id)
);